project:
  type: website
  output-dir: docs

website:
  favicon: "images/logo.png"
  title: "CS2007: Machine Learning Techniques"
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    background: "#D9E3E4"
  repo-url: https://github.com/SherryS997/MLT_notes
  site-url: "https://bsc-iitm.github.io/MLT_notes/"
  page-navigation: true
  open-graph: true
  sidebar:
    logo: "images/logo.png"
    background: "#D9E3E4"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/bsc-iitm/MLT_notes
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Home"
        contents: 
          - href: index.qmd
            text: Content
          - href: about.qmd
            text: About
      - section: "Notes"
        contents:
          - href: pages/Wk01.qmd
            text: Week-01
          - href: pages/Wk02.qmd
            text: Week-02
          - href: pages/Wk03.qmd
            text: Week-03
          - href: pages/Wk04.qmd
            text: Week-04
          - href: pages/Wk05.qmd
            text: Week-05
          - href: pages/Wk06.qmd
            text: Week-06
          - href: pages/Wk07.qmd
            text: Week-07
          - href: pages/Wk08.qmd
            text: Week-08
          - href: pages/Wk09.qmd
            text: Week-09
          - href: pages/Wk10.qmd
            text: Week-10

      - section: "Supplemental Notes"
        contents:
          - href: pages/Not01.ipynb
            text: Tutorial-01
          - href: pages/Not02.ipynb
            text: Tutorial-02
          - href: pages/Not03.ipynb
            text: Tutorial-03
          - href: pages/Not04.ipynb
            text: Tutorial-04
          - href: pages/Not05.ipynb
            text: Tutorial-05
          - href: pages/Not06.ipynb
            text: Tutorial-06
          - href: pages/Not07.ipynb
            text: Tutorial-07
          - href: pages/Not08.ipynb
            text: Tutorial-08
          - href: pages/Not09.ipynb
            text: Tutorial-09

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto
editor: visual
